version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: sks-netology-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      - ./alerts.yml:/etc/prometheus/alerts.yml:ro
    networks:
      sks-my-netology-hw:
        ipv4_address: 10.5.0.100
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  pushgateway:
    image: prom/pushgateway:latest
    container_name: sks-netology-pushgateway
    ports:
      - "9091:9091"
    networks:
      sks-my-netology-hw:
        ipv4_address: 10.5.0.101
    restart: unless-stopped
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: sks-netology-grafana
    ports:
      - "80:3000"
    volumes:
      - ./custom.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_CONFIG_FILE=/etc/grafana/grafana.ini
    networks:
      sks-my-netology-hw:
        ipv4_address: 10.5.0.102
    restart: unless-stopped
    depends_on:
      - prometheus
      - pushgateway

  alertmanager:
    image: prom/alertmanager:latest
    container_name: sks-netology-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    networks:
      sks-my-netology-hw:
        ipv4_address: 10.5.0.103
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  sks-my-netology-hw:
    name: sks-my-netology-hw
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
